ServerEvents.recipes(event => {
    //event.remove({input:})
    //event.remove({output:})
    event.remove({input: 'traveloptics:abyssal_spellweave_ingot'})
    event.remove({input: 'traveloptics:witherite_upgrade_smithing_template'})
    event.remove({output: 'traveloptics:hydrocharge_bracelet'})
    event.remove({output: 'traveloptics:cryostorm_bracelet'})
    event.remove({input: 'cataclysm_spellbooks:excel_upgrade_mana'})
    event.remove({input: 'cataclysm_spellbooks:excel_upgrade_cooldown'})
    event.remove({output: 'cataclysm_spellbooks:bloom_stone_hat'})
    event.remove({output: 'cataclysm_spellbooks:bloom_stone_chestplate'})
    event.remove({output: 'cataclysm_spellbooks:bloom_stone_skirt'})
    event.remove({output: 'cataclysm_spellbooks:bloom_stone_greaves'})
    event.remove({input: 'cataclysm_spellbooks:abyssal_rune'})
    event.remove({input: 'cataclysm_spellbooks:technomancy_rune'})
    event.remove({output:Item.of('cataclysm_spellbooks:monstrous_flamberge', '{Damage:0,ISB_Spells:{data:[{id:"cataclysm_spellbooks:tectonic_tremble",index:0,level:1,locked:1b}],maxSpells:1,mustEquip:0b,spellWheel:1b}}')})
    event.remove({output:Item.of('cataclysm_spellbooks:abyss_spell_book', '{ISB_Spells:{data:[],maxSpells:12,mustEquip:1b,spellWheel:1b}}')})
    event.remove({output:Item.of('cataclysm_spellbooks:ignis_spell_book', '{ISB_Spells:{data:[],maxSpells:12,mustEquip:1b,spellWheel:1b}}')})
    event.remove({output:Item.of('cataclysm_spellbooks:codex_of_malice_spell_book', '{ISB_Spells:{data:[],maxSpells:12,mustEquip:1b,spellWheel:1b}}')})
    event.remove({output:Item.of('cataclysm_spellbooks:disc_driver', '{ISB_Spells:{data:[],maxSpells:12,mustEquip:1b,spellWheel:1b},az_id:[I;-58560275,-585874096,-1227746107,-2087429263]}')})
    event.remove({output:Item.of('cataclysm_spellbooks:the_berserker', '{ISB_Spells:{data:[{id:"cataclysm_spellbooks:cryopiercer",index:0,level:1,locked:1b}],maxSpells:1,mustEquip:0b,spellWheel:1b},az_id:[I;-1025420749,1188577717,-1427866655,-1993607438]}')})
    event.remove({output:Item.of('cataclysm_spellbooks:the_combuster', '{ISB_Spells:{data:[{id:"cataclysm_spellbooks:scorched_earth",index:0,level:1,locked:1b}],maxSpells:1,mustEquip:0b,spellWheel:1b},az_id:[I;-1021194605,-88715799,-1437031080,-1344054575]}')})
    event.remove({output:Item.of('cataclysm_spellbooks:the_nightstalker', '{ISB_Spells:{data:[{id:"cataclysm_spellbooks:hemorrhaging_impact",index:0,level:1,locked:1b}],maxSpells:1,mustEquip:0b,spellWheel:1b},az_id:[I;-2008224302,1307853294,-1855970630,1360972272]}')})
    event.remove({output:Item.of('cataclysm_spellbooks:cursium_mage_circlet', '{Damage:0,ISB_Spells:{data:[],maxSpells:1,mustEquip:1b,spellWheel:1b}}')})
    event.remove({output:Item.of('cataclysm_spellbooks:cursium_mage_chestplate', '{Damage:0,ISB_Spells:{data:[],maxSpells:1,mustEquip:1b,spellWheel:1b}}')})
    event.remove({output:Item.of('cataclysm_spellbooks:cursium_mage_skirt', '{Damage:0}')})
    event.remove({output:Item.of('cataclysm_spellbooks:cursium_mage_boots', '{Damage:0}')})

})